// 生成小程序内置词典（紧凑单字符串格式，运行时切分，体积最小化）
// 用法：npm run gen-dict-mp
import fs from 'node:fs'
import path from 'node:path'

const rows = JSON.parse(fs.readFileSync('public/dict/dict.json', 'utf8'))
const sorted = [...rows]
  .sort((a, b) => (b.freq || 0) - (a.freq || 0))
  .slice(0, 7000)
  .map((d) => [
    d.w,
    (d.us || '').replace(/[|"'\\\n]/g, ''),
    (d.uk || '').replace(/[|"'\\\n]/g, ''),
    (d.pos || '').slice(0, 12).replace(/[|"'\\\n]/g, ''),
    (d.zh || '').slice(0, 100).replace(/[|"'\\\n\r]/g, ''),
    d.freq || 0,
  ])

// 单字符串：每行一条，字段用 | 分隔（字段内容已清洗，不含分隔符）
const RAW = sorted.map((r) => r.join('|')).join('\n')

const ts = `/**
 * AUTO-GENERATED by scripts/gen-dict-mp.mjs — do not edit
 * 小程序内置离线词典（按词频排序前 ${sorted.length} 词，紧凑字符串格式）
 * 每行：单词|美式音标|英式音标|词性|中文释义|词频星级
 */
const RAW = ${JSON.stringify(RAW)}

export interface DictRow {
  w: string
  us: string
  uk: string
  pos: string
  zh: string
  freq: number
}

export const DICT: DictRow[] = RAW.split('\\n').map((line) => {
  const [w, us, uk, pos, zh, freq] = line.split('|')
  return { w, us, uk, pos, zh, freq: Number(freq) || 0 }
})
`

const out = path.resolve(import.meta.dirname, '..', 'mp', 'src', 'data', 'dictData.ts')
fs.writeFileSync(out, ts)
console.log(`✅ 生成 ${out}（${sorted.length} 词条，源码 ${(ts.length / 1024).toFixed(0)} KB）`)
